<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>AgentLab</PackageId>
    <Version>1.0.1</Version>
    <Authors>Ahmed Haredy</Authors>
    <Description>AgentLab is a lightweight developer UI framework for Microsoft Agent Framework (MAF) that provides interactive chat, agent execution monitoring, workflow visualization, streaming events, and debugging tools for AI agent applications built with ASP.NET Core.</Description>
    <PackageTags>chat;ui;ai;agent;aspnetcore;chatbot</PackageTags>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>CS1591</NoWarn>
    <IsPackable>true</IsPackable>
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/ahmedharedy2006/AgentLab</RepositoryUrl>
    <PackageProjectUrl>https://github.com/ahmedharedy2006/AgentLab</PackageProjectUrl>
    <Copyright>Copyright (c) 2026 Ahmed Haredy</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <None Include="LICENSE" Pack="true" PackagePath="\" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
